### ISSUE TITLE
[SEVERE] Error while executing SDK Http request

### ISSUE THREAD

**Issue by Angelol1** [bonepl/ChromaLeague#100]
I am getting "[SEVERE] Error while executing SDK Http request" on the console when I try to start a game

**Comment by bonepl** [comment]
hi, can you share whole stacktrace of an error?

Do you have latest Synapse and checked if Chroma REST SDK service is up and running (check readme/troubleshooting on main page for some details)?

**Comment by Angelol1** [comment]
![part1](https://user-images.githubusercontent.com/34169575/116555612-97e29080-a8ca-11eb-83f2-81607abde666.png)
![part2](https://user-images.githubusercontent.com/34169575/116555620-9add8100-a8ca-11eb-8bd5-62ea2d92e981.png)


and yes I have Synapse updated and the powershell command says the the SDK service is up and running

**Comment by bonepl** [comment]
Looks like something is interrupting connection between Chroma League and Razer client. Do you have any traffic blocking software, antivirus, firewall etc that can be messing with the connection?

**Comment by Angelol1** [comment]
No I don't have any antivirus/firewall except for the windows one.

**Comment by bonepl** [comment]
Can you share the output of this link?
[https://chromasdk.io:54236/razer/chromasdk](https://chromasdk.io:54236/razer/chromasdk)

**Comment by Angelol1** [comment]
it says {"core":"3.20.01","device":"3.20.01","version":"3.20.01"}

**Comment by Angelol1** [comment]
Hello, it started working all of a sudden. Thanks for the help though!
