### ISSUE TITLE
Couldn't import batch file into synapse

### ISSUE THREAD

**Issue by xForsakenx** [bonepl/ChromaLeague#107]
![image](https://user-images.githubusercontent.com/89719020/131238591-d604af99-141b-44b7-8dc0-690cf881f9ed.png)

**Comment by bonepl** [comment]
Hi, this integration is not designed for import to Chroma Studio. Please run it with attached chroma-league.bat file.

**Comment by xForsakenx** [comment]
![image](https://user-images.githubusercontent.com/89719020/131292056-9f5aa2d5-a2df-453a-8bdc-f1187d496b36.png)
Based on your instruction, it doesn't show runs properly
