### ISSUE TITLE
how can i unapply this?

### ISSUE THREAD

**Issue by asdfehghxx** [bonepl/ChromaLeague#110]
it seems not working while playing league. 

chroma goes off when game starts, regardless of what i set up in synapse.

so i want to delete chromaleague, but don't know how to do that.

plaese help me.

**Comment by bonepl** [comment]
This is standalone application - just close it and delete from your disc.

**Comment by Henryivanaga** [comment]
I have the same problem. I already deleted the folder and reinstalled Synapse, but Chromaleague continues to work. I need to remove it.

**Comment by bonepl** [comment]
I'm sorry, but I don't understand what do you mean by "it continues to work". This is standalone application, it stops working the moment you close its window.
