### ISSUE TITLE
ChromaLeague does not work on ornata V2

### ISSUE THREAD

**Issue by JosepVargasf** [bonepl/ChromaLeague#113]
Hi, i'm trying to use ChromaLeague following the tutorial posted on this git. 
When i'm playing the console detects that i entered the game but no light appeard in my keyborad.
Here's the log
19:06:49 [INFO] Started Chroma League, close this window to exit the application
19:06:50 [INFO] Detected Razer Chroma REST Api Version[core=3.23.02, device=3.23.01, version=3.23.02]
19:06:50 [INFO] Running ChromaLeague version 1.1.4
19:06:50 [INFO] Your ChromaLeague version is up to date!
19:10:39 [INFO] Game is loading
19:10:59 [INFO] Player joined the game

**Comment by JosepVargasf** [comment]
Thank you for your work ! this looks amazing

**Comment by bonepl** [comment]
Hello, not sure now if it's working or not :)

**Comment by JosepVargasf** [comment]
Nvm, i restarted my pc and everything works well. :)
