### ISSUE TITLE
having a hard time making it work

### ISSUE THREAD

**Issue by fillv5** [bonepl/ChromaLeague#125]
might be my fault but i cant make it work.firstly i cant find a file named "chroma-league.bat" . secondly is there any tutorial ?
im on ornata v2

**Comment by bonepl** [comment]
![obraz](https://user-images.githubusercontent.com/72575496/146675821-4688099d-58e7-4322-8ad1-fd8a0877bf29.png)
This can be also named just "chroma-league" if you don't see file extensions (which are by default turned off in Windows)

**Comment by bonepl** [comment]
No tutorial, just run it, don't close the window, and go play some games

**Comment by bonepl** [comment]
hey @fillv5 please download latest 1.2.1 release and run with `run-chroma-league` file

**Comment by fillv5** [comment]
@bonepl my bad my man , i just didnt keep the window open . all good now
