### ISSUE TITLE
Sorry in advance

### ISSUE THREAD

**Issue by zamzam28** [bonepl/ChromaLeague#127]
This may be the wrong spot for this question, but I couldn't find another spot...So here goes I was getting back into League and was hoping to test out the lighting features. Unfortunately, I've had no luck getting the file to unpack and launch. Am i maybe doing something wrong?

**Comment by bonepl** [comment]
Can you describe the exact steps you're doing to run Chroma League? I need more details to help you.

**Comment by zamzam28** [comment]
I'm just having troubles getting it to launch. I have an original Ornata, but I think maybe I downloaded an update file instead of the actual chroma. I see it download but when I open the file I can't get it to unpack/extract the files.
I thought i got close a second ago but now it says "windows cannot find './cl-jre/bin/java.exe'. Make sure you type the name correctly and try again"

**Comment by bonepl** [comment]
You need to extract files from zip archive before running it. I know that windows has the opportunity to run files from inside archive - but that ends with the error you mention.

Right click on the zip release, choose "extract all", select directory of your choice and try running chroma-league from there.

**Comment by zamzam28** [comment]
I still can't seem to get it to open...Could I ask for a step by step to access it?  I just tried to do what yu said, extract all into my downloads, and my desktop. Unfortunately still no luck. That screenshot is where it deadends me.

![Screenshot (2)](https://user-images.githubusercontent.com/96559208/147376248-d60df1c8-64cf-4d27-9fda-00be89131cc9.png)

**Comment by bonepl** [comment]
You downloaded a sources repository instead of a release.
Newest release for now is this one:

 https://github.com/bonepl/ChromaLeague/releases/tag/v1.2.1

Download ChromaLeague-1.2.1.zip from there, try again and let me know.

sob., 25 gru 2021, 03:40 użytkownik zamzam28 ***@***.***>
napisał:

**Comment by zamzam28** [comment]
Thank yu sir, I did get it working with a shortcut setup. How long did all of this take yu to make?

**Comment by bonepl** [comment]
It's an ongoing work, i have lost count of development and testing hours :)

niedz., 26 gru 2021, 16:32 użytkownik zamzam28 ***@***.***>
napisał:

**Comment by zamzam28** [comment]
Is there a list of champions it works with, or is it mostly just the rift and the hud?

**Comment by bonepl** [comment]
All champions are supported, but it also depends on what exactly are you asking about.

**Comment by zamzam28** [comment]
I was thinking the keys lit up differently for some champs than others...and I thought I read something about an Ult mechanic

**Comment by bonepl** [comment]
There are differences between champions in resource bar which will light up blue for remaining mana, but for example Sett will have it's Grit passive indicated there in yellow and animations depending on the Grit fill.

I don't know what ult mechanic are you referring to.
