### ISSUE TITLE
Missing Cool Down animations and spell animations

### ISSUE THREAD

**Issue by bmck1124** [bonepl/ChromaLeague#128]
Hey, sorry if this was addressed before, I searched for an answer but was having trouble finding one. I run the program and most of the animations work which is great. But, it seems a few aren't working, spell animations aren't working for champions and the cooldown tracker for spells aren't working either. I'm having trouble figuring out how to fix it. I made sure there wasn't any other profiles running that could interfere but I can't seem to find a fix. Any help would be greatly appreciated thanks.

**Comment by bonepl** [comment]
Hi, things you mentioned are not supported by ChromaLeague, please take a look at what's supported at
https://github.com/bonepl/ChromaLeague#implemented-integrations
