### ISSUE TITLE
running it 

### ISSUE THREAD

**Issue by gurasa1** [bonepl/ChromaLeague#131]
i cant run it how to unpack it fully and its showing windows cannot find './cl-jre/bin/java.exe'.
idk how to unpack it fully and what to do plz make more detailed instruction

**Comment by gurasa1** [comment]
also i have extracted it But still same error plz help

**Comment by bonepl** [comment]
Can you describe step by step how are you trying to run Chroma League?

**Comment by gurasa1** [comment]
i downloaded newest version 1.2.1 extracted it and runned "run-chroma-league.bat" as administrator and its showing windows cannot find './cl-jre/bin/java.exe'. @bonepl

**Comment by bonepl** [comment]
Does the directory where you execute run-chroma-league have cl-jre directory?

Can you share the screenshot?

Also you don't need to run CL as administrator.

**Comment by gurasa1** [comment]
do you have discord or something ? im gonna mute myself share screen and show u

**Comment by gurasa1** [comment]
when im not running cl as administrator it just opens and closes and does nothing

**Comment by gurasa1** [comment]
![image](https://user-images.githubusercontent.com/98217080/150647572-a0b584b8-bc7d-4987-985f-96868af7c5b6.png)

**Comment by gurasa1** [comment]
@bonepl

**Comment by bonepl** [comment]
This looks fine, in cl-jre directory - do you have bin/java.exe as in the error message?

**Comment by gurasa1** [comment]
> This looks fine, in cl-jre directory - do you have bin/java.exe as in the error message?

error message is shown on screenshot

**Comment by gurasa1** [comment]
yes ithink

**Comment by gurasa1** [comment]
@bonepl

**Comment by gurasa1** [comment]
> This looks fine, in cl-jre directory - do you have bin/java.exe as in the error message?

yes i do

**Comment by gurasa1** [comment]
@bonepl now its showing its up to date
![image](https://user-images.githubusercontent.com/98217080/150652183-a5082bf5-d230-44c0-a72b-54a4ad955540.png)

**Comment by bonepl** [comment]
This is what we want it to say. Try running the game now, practice mode is enough :)
