### ISSUE TITLE
Error on start 

### ISSUE THREAD

**Issue by KarolusRex111** [bonepl/ChromaLeague#135]
Hi can you help me with this ? 
![obraz_2022-02-20_184846](https://user-images.githubusercontent.com/93391047/154856476-d876b449-b7c8-494a-bc9d-9537e4dea715.png)

**Comment by bonepl** [comment]
Hi, can you tell me what this address returns in your browser?
http://localhost:54235/razer/chromasdk

**Comment by KarolusRex111** [comment]
> Hi, can you tell me what this address returns in your browser? http://localhost:54235/razer/chromasdk

Well nowhere, it doesn't work for me

**Comment by bonepl** [comment]
Do you have Razer Synapse installed with Chroma Connect module enabled?

**Comment by KarolusRex111** [comment]
Yea,it was working before, it stopped working few days ago

**Comment by bonepl** [comment]
Is Razer Chroma SDK Server service in Windows (services.msc) up and running?

**Comment by KarolusRex111** [comment]
That was it! it was disabled for some reason, thank you so much. Have a great day
