### ISSUE TITLE
Problem with my Keyboard

### ISSUE THREAD

**Issue by Burak309** [bonepl/ChromaLeague#137]
Hello, I love what you have created here and respect how much time you have invested in it and what details you pay attention to.
My Blackwidow Elite keyboard doesn't work even though I installed everything according to your instructions. I have almost no experience with coding or scripting, but I would be very happy if you could help me.

**Comment by bonepl** [comment]
Can you share more info about what's not working? Can you share logs of app?

**Comment by bonepl** [comment]
you need to enter the game to start integration, you can try this on some practice mode

**Comment by Burak309** [comment]
Thank you for your quick reply . I haven't tried it that way yet. Thank you very much for your quick reply and I'm very sorry that I took up your time for something like this. It works and I'm very satisfied thanks again.
