### ISSUE TITLE
chroma league doesnt work ingame

### ISSUE THREAD

**Issue by Chischwi** [bonepl/ChromaLeague#144]
I downloaded the chroma league and it passed the startup checks. But it doesnt seem to work when i play League. I already checked services.msc and the razer server is running.

**Comment by Chischwi** [comment]
cl.log:
01:09:33 [INFO] Started Chroma League, close this window to exit the application
01:09:34 [INFO] Detected Razer Chroma REST Api Version[core=3.31.00, device=3.31.00, version=3.31.00]
01:09:34 [INFO] Running ChromaLeague version 1.2.1
01:09:34 [INFO] Your ChromaLeague version is up to date!
01:11:05 [INFO] Started Chroma League, close this window to exit the application
01:11:05 [INFO] Detected Razer Chroma REST Api Version[core=3.31.00, device=3.31.00, version=3.31.00]
01:11:06 [INFO] Running ChromaLeague version 1.2.1
01:11:06 [INFO] Your ChromaLeague version is up to date!

**Comment by bonepl** [comment]
hmm, it looks like there are some problems with game detection.
Once you are in game, can you check in browser what does this address return?
https://127.0.0.1:2999/liveclientdata/eventdata

and paste the result here?

**Comment by Chischwi** [comment]
nvm i figured it out, but thanks for the fast response.
