### ISSUE TITLE
关于打不开runchroma

### ISSUE THREAD

**Issue by 123wzy666** [bonepl/ChromaLeague#145]
您好，您需要将存档完全解压缩到单独的目录  是什么意思   出现找不到“./cl-ire/bin/iava.exe”如何解决？
[ChromaLeague-1.2.1.tar.gz](https://github.com/bonepl/ChromaLeague/files/11715442/ChromaLeague-1.2.1.tar.gz)

**Comment by bonepl** [comment]
hi, please follow the instructions on the main page for ChromaLeague installation
