### ISSUE TITLE
"Your ChromaLeague version is up to date!" Problem

### ISSUE THREAD

**Issue by CyberneticWar** [bonepl/ChromaLeague#147]
![Problem](https://github.com/bonepl/ChromaLeague/assets/50974550/54d2aab6-0a3f-4fdf-a27b-2e89b939f887)

Hi, when i open the ChromaLeague, the app still doesn't run and stop it at this point..How can i solve it?

**Comment by bonepl** [comment]
Hi, have you tried joining the game? CL should automatically detect when you join the game.

**Comment by z0nezz** [comment]
I have the same issue. Any fix around this? i've tried to troubleshoot it.

**Comment by bonepl** [comment]
Unfortunately I am not able to reproduce this - everything seems to work fine on the same Razer version and newest LoL. Have you tried fully reinstalling Razer Synapse?

**Comment by bonepl** [comment]
Hi, check newest release [Chroma League 1.3.0](https://github.com/bonepl/ChromaLeague/releases/tag/v1.3.0) if it fixes the problem for you.

**Comment by bonepl** [comment]
Hey @CyberneticWar and @z0nezz have you tried the newest version of ChromaLeague?

**Comment by bonepl** [comment]
No response from reporter
