### ISSUE TITLE
Chroma league not working in league window but works everywhere else

### ISSUE THREAD

**Issue by rominouuu** [bonepl/ChromaLeague#148]
Hello,
I have an issue where Chroma League works great, everything is okay. However, when I'm on the League window, the keyboard turns black and nothing is displayed anymore. Then, when I Alt-tab to any other window, it works again.

I hope the issue hasn't been addressed yet. 
Thanks in advance !

**Comment by rominouuu** [comment]
OK its my bad sorry. I had a profile linked to lol. So when the active tab was league, the keyboard was turning black but now that i deleted the profile everything works...
Sorry for the loss of time and thanks for help !

**Comment by bonepl** [comment]
No problem, glad it works
