### ISSUE TITLE
Name error

### ISSUE THREAD

**Issue by CamiloSilva28** [bonepl/ChromaLeague#150]
I get the error caused by having  an 'ñ' on my name.

**Comment by bonepl** [comment]
Hi, can you share the output of following pages while you are in game?

https://127.0.0.1:2999/liveclientdata/activeplayer

https://127.0.0.1:2999/liveclientdata/playerlist

https://127.0.0.1:2999/liveclientdata/activeplayername

You can use something like https://pastebin.com and share the link with me.

**Comment by CamiloSilva28** [comment]
Player list: https://pastebin.com/dz4Qu8yL
Active player: https://pastebin.com/YT9iiXyM
Active Player Name: "PiñaDescroto#LOW"

**Comment by bonepl** [comment]
Hi, check newest release [Chroma League 1.3.0](https://github.com/bonepl/ChromaLeague/releases/tag/v1.3.0) if it fixes the problem for you.
