### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by guiimiii** [bonepl/ChromaLeague#151]
HI, i get this message when i open Bat file : 

SEVERE] Error while executing SDK Http request org.apache.http.conn.HttpHostConnectException: Connect to localhost:54235 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
 
<img width="1125" alt="image" src="https://github.com/bonepl/ChromaLeague/assets/153933343/2237386f-d009-4103-987c-ca228c471dc7">
 
Plus i noticed that when i launch as admin the bat i get that error although i extracted everything
<img width="425" alt="image" src="https://github.com/bonepl/ChromaLeague/assets/153933343/e0c235d9-b96b-4235-81cd-8b1170a74dcc">

Thanks a lot for this mod, it looks great

**Comment by bonepl** [comment]
Hi, please follow the front page instructions closely. You don't need to run Chroma League as administrator. If problem still persists try reinstalling Razer Synapse.

**Comment by bonepl** [comment]
Hi @guiimiii have you tried reinstalling Razer Synapse?

**Comment by guiimiii** [comment]
Hi,
Yes and still the same issue. I also tried version 1.3.0, still the same :/
<img width="1035" alt="image" src="https://github.com/bonepl/ChromaLeague/assets/153933343/9ebf7a82-26da-483d-a2b4-c09bfb116954">

**Comment by bonepl** [comment]
Can you check if you're able to access this page after entering the game?

https://127.0.0.1:2999/liveclientdata/activeplayer

What does it return?

**Comment by guiimiii** [comment]
Ok it works ! I just need to launch the game and when in game i launch the bat file... The mod is soo cool thanks !

**Comment by bonepl** [comment]
Glad it worked for you
