### ISSUE TITLE
How to unpack the archive to separate directory, here is full of error

### ISSUE THREAD

**Issue by Jarrod29** [bonepl/ChromaLeague#158]
![Uploading image.jpg…]()

**Comment by bonepl** [comment]
Can you try describing your issue again? Something went wrong.

**Comment by Jarrod29** [comment]
I mean when I have download your chroma league-1.3.0, What should I do then when I clicked into the launcher—-run chroma league.bat , it will go error.

Uploading 72720681255__F6BA2646-08B6-4F03-8AFF-0434C6175BEA.MOV…

**Comment by bonepl** [comment]
Can't see your attachments, still not sure what is your error.

**Comment by Jarrod29** [comment]
![image](https://github.com/bonepl/ChromaLeague/assets/156942842/da9c96d8-565c-49cc-84f2-563375b5e51f)
Oh, here’s the question, I don’t understand, how to unpack the archive to separate directory before running it???

**Comment by bonepl** [comment]
Right click on a zip archive and look for something like unpack or extract everything.

**Comment by Jarrod29** [comment]
When I unpacked the zip, and click the run, it’s error 
![Uploading image.jpg…]()

**Comment by Jarrod29** [comment]
Do I need to cover the new version with original version of the file?

**Comment by bonepl** [comment]
I'm not sure I got it - you can remove the old version and use everything from the newly downloaded release zip archive. Still can't see most of your attachments.

**Comment by Jarrod29** [comment]
It’s so sorry to interrupt you, I still can’t solve the problems, if you don’t mind, can you give me your Instagram account?

**Comment by Jarrod29** [comment]
Pardon me,sorry, I have unpacked all the things that downloaded from your address, the latest one. Every time when I went into chroma league launcher and clicked The run, It will be the error, Windows cannot find/cl-jre/bin/java.exe. I found The archive I downloaded, it didn’t have/cl-jre/bin

**Comment by bonepl** [comment]
Please read the installation instructions carefully. There is a description of this exact problem

**Comment by Jarrod29** [comment]
I really don’t know what’s going on here, I have no clue. I read the instruction and where I don’t understand is that you need to fully unpack archive to separate directory before running it. What does it mean

**Comment by bonepl** [comment]
https://support.microsoft.com/en-us/windows/zip-and-unzip-files-f6dde0a7-0fec-8294-e1d3-703ed85e7ebc

Maybe this official Microsoft instruction will help you.

**Comment by Jarrod29** [comment]
no this wont help,did i do something wrong when i download ur zip?i saw 3 packs should i download them all?cause i downloaded just the first one,im wondering it is the problem.
![微信图片_20240118170959](https://github.com/bonepl/ChromaLeague/assets/156942842/6bb05999-0460-42cc-9bb9-113238dce9d7)
![微信图片_20240118171005](https://github.com/bonepl/ChromaLeague/assets/156942842/bbedf641-be1f-4278-8fd7-047b5af4d288)
is it lack of some files????

**Comment by bonepl** [comment]
You have downloaded repository itself not the release. Try downloading this file: https://github.com/bonepl/ChromaLeague/releases/download/v1.3.0/ChromaLeague-1.3.0.zip

**Comment by Jarrod29** [comment]
I got this thank you so much it can work well,love you!
