### ISSUE TITLE
Error while drawing main HUD

### ISSUE THREAD

**Issue by MrsTomahawk** [bonepl/ChromaLeague#159]
Im a noob if it comes to all this but im getting this error. 

![image](https://github.com/bonepl/ChromaLeague/assets/157623610/70741846-1aac-4372-9c5b-c019f8dfc6d3)

**Comment by bonepl** [comment]
Hi what version of ChromaLeague are you using? Can you try running the latest one? https://github.com/bonepl/ChromaLeague/releases/download/v1.3.0/ChromaLeague-1.3.0.zip

**Comment by MrsTomahawk** [comment]
Hii i downloaded the only version that’s on here. 1.3.0

**Comment by MrsTomahawk** [comment]
wait a second i'm sure i used that link but it says 1.0.1 in my folder

im a bit confused now let me try to redownload it.

**Comment by bonepl** [comment]
Logs look ok, do you have any other integrations working on your keyboard that could interfere? Is your keyboard going dark when you enter the game? What model of keyboard do you have?

**Comment by MrsTomahawk** [comment]
i do not think so, could i be i have to turn of certain things in synapse? 

Razer Blackwidow V3

**Comment by bonepl** [comment]
Can you try fully reinstalling Razer Synapse and just install it with basic setup and Chroma enabled (like in instructions)? And see if that solves your issue?

**Comment by MrsTomahawk** [comment]
i reinstalled synapse, even continued as quests, i turned everything off only Chroma league is on.

still nothing changes on my keyboard.

![image](https://github.com/bonepl/ChromaLeague/assets/157623610/f443b6e5-ecd7-41c0-b8f5-7d2c6a0a2b45)

**Comment by MrsTomahawk** [comment]
this from after the reinstall, i tested it also on a different account where i dont have a special letter in my name.

![image](https://github.com/bonepl/ChromaLeague/assets/157623610/950b3734-7bc4-455a-9b8e-bd311ce7092b)

**Comment by bonepl** [comment]
If lights remain the same - can you try turning off keyboard lightning fully and then try running Chroma League? I'm wondering if default lightning isn't overriding CL's session

**Comment by MrsTomahawk** [comment]
sorry if i sound stupid but where exactly do i do that? here?

![image](https://github.com/bonepl/ChromaLeague/assets/157623610/a3db9c3a-ab11-44fe-a93a-b729b69d6d63)

**Comment by MrsTomahawk** [comment]
omg i found the problem i feel so stupid 

Chroma apps in the right top corner was turned off 

![image](https://github.com/bonepl/ChromaLeague/assets/157623610/69ec8b67-5037-4f20-9f62-8641f96b8f50)

**Comment by MrsTomahawk** [comment]
but the turn onn or off doesnt show when you click on one of the apps, after i pressed X it showed. lol thank you for your help and patience haha

**Comment by bonepl** [comment]
Should I add something to my instructions to guide other users?

**Comment by MrsTomahawk** [comment]
i do recommand that yes, if people like me who first time using any of this that could help alot

**Comment by MrsTomahawk** [comment]
oh 1 more question, on the razer website it does say that when with certain champs you use an ability the keyboard changes. like with Vel'koz. im not seeing that. is that not added yet? or is the site simply mistaken? haha

![image](https://github.com/bonepl/ChromaLeague/assets/157623610/0ff47163-3842-4a9f-a8de-6f2f8a822558)

**Comment by bonepl** [comment]
Can you paste me a link to the website where you have found this? There was some other integration that did that but as far as I know it has been abandoned long time ago. There is a lost of supported animations on the main page of Chroma League's GitHub

**Comment by MrsTomahawk** [comment]
i am so sorry we didnt internet anymore, huge black out in germany. 

here is the website. 

https://www.razer.com/chroma-workshop#--all--look--cmlvdCUyMGdhbWVzL2xlYWd1ZSUyMG9mJTIwbGVnZW5kcw_-__-_

**Comment by bonepl** [comment]
Thanks, screenshots are from different integration (not Chroma League). I will contact Razer staff to fix this.
