### ISSUE TITLE
feature: Light up ability keyboard buttons when ability isn't not on cooldown

### ISSUE THREAD

**Issue by FobbanN12** [bonepl/ChromaLeague#165]
It would be cool if the ability keyboard buttons (QWER) is lighted up when the abilities are ready

**Comment by bonepl** [comment]
I thought about this feature but I keep in mind that not everyone has the same hotkeys (I'm not playing QWER and find it very uncomfortable ;) )

And I don't have a way to access hotkeys mapping through LoL API so I could react to these.

And in-game LoL API doesn't have any generic data to track usage of skills.

**Comment by FobbanN12** [comment]
Okay I understund.

Thanks anyways!
