### ISSUE TITLE
is there a way to uninstall?

### ISSUE THREAD

**Issue by Snakeye112** [bonepl/ChromaLeague#167]
it stopped league from working on my PC. Is there any way to uninstall it?

**Comment by bonepl** [comment]
What do you mean "it stopped League working"?

Chroma League is portable app and does not require installation/uninstallation.

It won't work if you don't run it in the background.

You can check if there are some leftovers registered in Chroma Apps in Razer Synapse though, not sure about these

**Comment by Snakeye112** [comment]
i used the latest chroma league release, extracted the file and run the .bat, it then said it detected the league API or something like that and finished. however, it doesn't show up anywhere, and synapse can't find anything. i then tried going into a league game and got in, but it was buggy and the keyboard remained black. i tried restarting PC and now it opens the launcher and lets me search for a match, but wont load the game and cant even open the game window. is there any way to undo or remove whatever the .bat file did?

**Comment by Snakeye112** [comment]
im not sure what was wrong with it, but after running the .bat, I couldn't even open the league match window. I'm currently trying restarts and reinstalls of the synapse to see if it fixes anything, but I have a queue timer from missing matches, so its slow testing if anything works.

**Comment by Snakeye112** [comment]
if i want to get rid of any chance of it running in the background, can I just delete the downloaded files?

**Comment by Snakeye112** [comment]
Okay, I deleted all the files, reinstalled Synapse, and all that, and I think it's working fine now. I had to restart a few times, though.
