### ISSUE TITLE
problem for keyboard without the numeric keypad

### ISSUE THREAD

**Issue by tych3nn** [bonepl/ChromaLeague#170]
Hello! Thank you very much, but I am using a keyboard without a numeric keypad, so it seems that the script encountered some issues, as shown in the picture. Could you please provide a version suitable for a keyboard without a numeric keypad?😉
![a46d36168313e4e9461228e41ee14e7b](https://github.com/user-attachments/assets/fe4fa584-7ac7-4f9c-9b35-f2f6618e2c82)
![06e0c7501397162fc7beeea77515ff3f](https://github.com/user-attachments/assets/4bb67911-d70c-492a-afb5-44b41b35dcd9)

**Comment by bonepl** [comment]
Hello, can you share a .log file that should be in the same directory as ChromaLeague executable?

Apart from exceptions, are other animations working for you?

**Comment by tych3nn** [comment]
Thank you very much for your reply! This is my log file. The animation process is shown in the two videos. Due to the large file size, the videos are divided into "1" and "2" videos.


[cl.log.zip](https://github.com/user-attachments/files/17924041/cl.log.zip)

https://github.com/user-attachments/assets/37dce9a2-542e-432a-9c34-b45afb8d0185

https://github.com/user-attachments/assets/a3be2b83-4b78-4e95-8907-d0fdeaecba74

**Comment by bonepl** [comment]
Thanks for the videos and the log file. Everything is working fine. Log file is showing errors that it cannot connect to GitHub to check what is the newest version (you are probably behind a firewall) - you would need to check it by yourself at the release page. 

The numeric pad is responsible for gold visualization - apart from that, you should have every other animation working.

**Comment by bonepl** [comment]
I released new version that should stop throwing these errors, if there are any problems with other animations, let me know by reopening this issue
