### ISSUE TITLE
Rewrite to use Razer REST SDK instead of native C++

### ISSUE THREAD

**Issue by bonepl** [bonepl/ChromaLeague#76]

**Comment by hacker1024** [comment]
Hi, what motivated you to do this?

**Comment by bonepl** [comment]
I had unexpected errors and problems coming from C libs with memory
management. Using rest is much easier and industry standard and these
services are built just on top of C libs so there shouldn't be any visible
performance loss.

niedz., 12 gru 2021, 11:47 użytkownik hacker1024 ***@***.***>
napisał:
