### ISSUE TITLE
Problems with cl-jre

### ISSUE THREAD

**Issue by pelolsen** [bonepl/ChromaLeague#95]
Hello, I'm having problems launching the app. It says: "Windows can not find (...). Control that you wrote the correct name and try again." 
I've already tried to press on the cl-jre generator, but it does not seems to work.
![Skærmbillede 2021-03-24 195557](https://user-images.githubusercontent.com/70531026/112368074-fa98a900-8cda-11eb-90e8-2f212211b244.png)
Is there anyway to fix this issue?
Thanks a lot
Patrick

**Comment by bonepl** [comment]
Hello, have you moved `chroma-league.bat` out of the directory?
It needs to be in the same directory as `cl-jre`
![obraz](https://user-images.githubusercontent.com/72575496/112369103-20727d80-8cdc-11eb-8c53-fd6dadb927c1.png)

**Comment by pelolsen** [comment]
![image](https://user-images.githubusercontent.com/70531026/112375242-58c98a00-8ce3-11eb-9538-3dc4bb1ee3cd.png)
Nothing has been moved. I dont even have that folder.
Just to check if I am on the right directory, thats where I am accessesing the chroma-league.bat:
C:\Users\pelol\Documents\ChromaLeague-master\chroma-league-launcher\src\scripts

**Comment by pelolsen** [comment]
I've downloaded the code in a ZIP-file and unpacked it on my Documents folder.

**Comment by bonepl** [comment]
I'm afraid that won't work that way :)
Please download latest zip file (not source code) from [releases](https://github.com/bonepl/ChromaLeague/releases) and try running it that way.

Currently the latest release is [Chroma League 1.1.0](https://github.com/bonepl/ChromaLeague/releases/tag/v1.1.0)

**Comment by pelolsen** [comment]
It’s working properly now. Thanks a lot for the help. It was Razers website that redirected me to the wrong page.

**Comment by bonepl** [comment]
No problem
